name: Build application

on:
  release:
    types:
      - published

jobs:

  build-android:

    runs-on: ubuntu-latest

    env:
      RELEASE_ARTIFACT: MineSweeper.apk

    steps:
      - name: ⚙️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: ⚙️ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install --production

      - name: 🚀 Build app
        run: eas build --non-interactive --platform android --profile preview

      - name: 📥 Download built artifact
        run: |
          ARTIFACT_URL=$( eas build:list --platform android --status finished --limit 1 --json --non-interactive | jq -r '.[].artifacts.buildUrl' )
          wget "$ARTIFACT_URL" -O ${{ env.RELEASE_ARTIFACT }}

      - name: 💣 Upload release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ${{ env.RELEASE_ARTIFACT }}
